### ISSUE TITLE
Guide for creating and installing IWA

### ISSUE THREAD

**Issue by rck1** [WICG/isolated-web-apps#23]
Can someone point me to a good guide/resource for creating and installing isolated web apps?  Information is sparse on the web.  I'm looking for a step-by-step guide.

**Comment by reillyeon** [comment]
Given that this proposal is still under development we don't have polished developer documentation ready. The [telnet-client](https://github.com/googlechromeLabs/telnet-client) repo provides a demo application with the necessary build system configuration for building a signed web bundle and instructions for how to load it in Chrome. We try to keep this example up-to-date as the implementation evolves.

**Comment by rck1** [comment]
Thank you @reillyeon .  I did come across the telnet demo.  Looks interesting.  I'll try working through that example.  My use case is very similar to #15, i.e. distribute web packages (via web bundles) without a web server.

I see in the telnet example, you can use the command line flag --install-isolated-web-app-from-file when launching Chrome.  I assume this is for development purposes and the final spec will allow you to install the IWA in a more user-friendly way.   Can you share any insights on what this might look like?  Similar to #15, I am hoping for a "navigate-to-web-bundle" functionality that was removed from Chrome earlier this year.  By enabling this experimental flag, you were able to simply drag and drop the .wbn file to the browser and it would launch the web app.  Can you share when you expect this feature to be available in Chrome for isolated web apps?

**Comment by cmfcmf** [comment]
> I see in the telnet example, you can use the command line flag --install-isolated-web-app-from-file when launching Chrome. I assume this is for development purposes and the final spec will allow you to install the IWA in a more user-friendly way.

Yes, indeed. The flag is only intended for development, and not for end-users.

> Can you share any insights on what this might look like? Similar to #15, I am hoping for a "navigate-to-web-bundle" functionality that was removed from Chrome earlier this year. By enabling this experimental flag, you were able to simply drag and drop the .wbn file to the browser and it would launch the web app.

We haven't fully worked out all of the details yet, but we plan to have something similar to this behavior for IWAs. One difference compared to the removed functionality for `.wbn` files is that you won't be able to open IWAs without installing them. 'Installing' here means going through some form of installation wizard, where the user confirms that they would like to install the IWA. Our current thinking is that the installation wizard for an IWA will probably open when you double-click a `.swbn` file.

> Can you share when you expect this feature to be available in Chrome for isolated web apps?

Work on the installation wizard has not yet started, so it is going to be a while.

**Comment by rck1** [comment]
Excellent, thank you for the rundown @cmfcmf.  This is exactly what we are looking for.  I'll continue keeping tabs on this.  Thanks to you and your team for advancing this important spec.
