### ISSUE TITLE
Isolation of PWAs

### ISSUE THREAD

**Issue by arikw** [WICG/isolated-web-apps#7]
Hello,
Thank you for your work.

There are PWAs that are offline in nature, and they don't need to use communications for their operation.
For example, a calculator of sorts.
As a user, I would like the ability to turn any PWA to an isolated one, and more specifically, prevent any data from being sent elsewhere.

Is this something you might consider?

**Comment by reillyeon** [comment]
I think this is the same as the suggestion in #1. It is something I have considered and should be possible (more details on that issue) but is not one of the initial goals of this project.
